[package]
name = "fcm"
version = "0.6.0"
authors = [
  "Suvish Varghese Thoovamalayil <vishy1618@gmail.com>",
  "panicbit <panicbit.dev@gmail.com>",
  "Julius de Bruijn <pimeys@gmail.com>"]
description = "An API to talk to FCM (Firebase Cloud Messaging) in Rust"
license = "MIT"
homepage = "https://github.com/panicbit/fcm-rust"
repository = "https://github.com/panicbit/fcm-rust"
documentation = "https://panicbit.github.io/fcm-rust/fcm/"
keywords = ["fcm", "firebase", "cloud", "messaging", "tokio"]

[dependencies]
serde = "1.0"
serde_json = "1.0"
erased-serde = "0.3"
serde_derive = "1.0"
futures = "0.1"
tokio-service = "0.1"
hyper = "0.12"
hyper-tls = "0.3"
http = "0.1"
chrono = "0.4"

[dev-dependencies]
argparse = "0.2.1"
tokio = "0.1"
